### ISSUE TITLE
Customer requests different Error message for AD Groups

### ISSUE THREAD

**Issue by raderag** [hvanalytics/HVATrayApp#11]
The Current message is "An AD group has not been set", but the customer would like it to be "AN AD group has not been set". 

Justin's comments:
It literally means no one went in and set a user group to compare against
There should be a separate message if the group IS set and the user IS NOT apart of it

We should keep the first message, but add the second in the proper situation.

**Comment by jfid1** [comment]
We have messages for 2 scenarios: 
1) "An AD group has not been set" - No one set the AD group upon install.  If no AD group is set, the bar will never show.

2) "User 'username' is not a member of the HVA group." - The user is not a member of the designated HVA AD groups.  The bar will not show for this user.
