### ISSUE TITLE
Bar show/hide timing.

### ISSUE THREAD

**Issue by jfid1** [hvanalytics/HVATrayApp#3]
Bar slow to hide/show.  Sometimes doesn't show initially.  Need to break the loop redundancy loop.

**Comment by raderag** [comment]
Changed timer type and added timer initiation for WindowEval() call in KeyboardHookProc().

**Comment by jfid1** [comment]
Made sure timers were cleared and routines were stopped when the bar is called to Hide.  I do suspect there might be another break point.  The fix is in "Justin" repo until I completely test it.  This fix is curretnly deployed on VM3 if anyone would like to test.
